### PR TITLE
Fix build for cross-compilation

### LINKED ISSUE #22: Unable to build 0.2.2.
Hi! I've been trying to use this crate, as (so far as I can tell) it's the only one that allows any sort of access to software PWM. Unfortunately, I can't compile, either in a native scenario, or in a cross-compilation scenario.

If I try to cross-compile, I get an error like:

```bash
Compiling wiringpi-color-test v0.1.0 (file:///mnt/c/Users/nmca/source-code/wiringpi-color-test)
error: linking with `arm-linux-gnueabihf-gcc` failed: exit code: 1
  |
  = note: "arm-linux-gnueabihf-gcc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-L" "/home/pingzing/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1.wiringpi_color_test0.rcgu.o" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1.wiringpi_color_test1.rcgu.o" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1.wiringpi_color_test10.rcgu.o" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1.wiringpi_color_test11.rcgu.o" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1.wiringpi_color_test12.rcgu.o" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1.wiringpi_color_test13.rcgu.o" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1.wiringpi_color_test14.rcgu.o" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1.wiringpi_color_test15.rcgu.o" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1.wiringpi_color_test2.rcgu.o" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1.wiringpi_color_test3.rcgu.o" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1.wiringpi_color_test4.rcgu.o" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1.wiringpi_color_test5.rcgu.o" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1.wiringpi_color_test6.rcgu.o" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1.wiringpi_color_test7.rcgu.o" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1.wiringpi_color_test8.rcgu.o" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1.wiringpi_color_test9.rcgu.o" "-o" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/wiringpi_color_test-06bee567defb01c1.crate.allocator.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs" "-L" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps" "-L" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/debug/deps" "-L" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/build/wiringpi-f1bbe22b8925abd3/out" "-L" "/home/pingzing/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib" "-Wl,-Bstatic" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/libwiringpi-79f6c45859f16f99.rlib" "/mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/liblibc-0eabc565922130ce.rlib" "/home/pingzing/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libstd-7e232c9c9bca57e9.rlib" "/home/pingzing/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libpanic_unwind-167b5e977a2ab35c.rlib" "/home/pingzing/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/liballoc_jemalloc-17deae1aa65c9467.rlib" "/home/pingzing/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libunwind-b8892ba833aa6677.rlib" "/home/pingzing/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/liballoc_system-17235785be0fea01.rlib" "/home/pingzing/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/liblibc-2e9b8cf09e3563de.rlib" "/home/pingzing/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/liballoc-d7195d5e94bc6586.rlib" "/home/pingzing/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libstd_unicode-963f18f265d9b8d3.rlib" "/home/pingzing/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libcore-48934815da5d2bfb.rlib" "/home/pingzing/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libcompiler_builtins-a6b6fad6cc543169.rlib" "-Wl,-Bdynamic" "-l" "util" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util"
  = note: /mnt/c/Users/nmca/source-code/wiringpi-color-test/target/arm-unknown-linux-gnueabihf/debug/deps/libwiringpi-79f6c45859f16f99.rlib: error adding symbols: File format not recognized
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: Could not compile `wiringpi-color-test`.

To learn more, run the command again with --verbose.
```

If I try to compile this same project directly on the Raspberry Pi, I get something that looks like this:

```bash
cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling wiringpi v0.2.2 (file:///home/pi/applications/rust-wiringpi)
   Compiling libc v0.2.36
error: could not find native static library `wiringpi`, perhaps an -L flag is missing?

error: Could not compile `wiringpi`.

To learn more, run the command again with --verbose.
```

Any advice on how I might overcome this?

### PR DESCRIPTION
**Pull request by yuhe00**
I got this working with my setup, cross-compiling from x86 to RPi using `arm-linux-gnueabihf-gcc`. 

Closes #22

### CODE REVIEW

**Comment by Ogeon** [comment]
Ah, I wonder if this will fix #22.

File: build.rs [hunk 1]
```diff
@@ -10,13 +10,17 @@ fn main() {
     if cfg!(feature = "development") {
         return;
     }
-    if let Ok(target) = env::var("TARGET") {
-        if !target.starts_with("arm-") {
```
Comment (Ogeon) [inline build.rs:14]: Some variant of this is still necessary to be able to automatically generate documentation without building the C library, but this check could be smarter.

File: build.rs [hunk 2]
```diff
@@ -10,13 +10,17 @@ fn main() {
...
-            return;
-        }
-    }
 
     let out_dir = env::var("OUT_DIR").unwrap();
+
+    let target = env::var("TARGET").unwrap();
+    match target.as_str() {
+        "armv7-unknown-linux-gnueabihf" => {
+            env::set_var("CC", "arm-linux-gnueabihf-gcc");
```
Comment (Ogeon) [inline build.rs]: We have to be careful and avoid overwriting `CC` if it's already set from the outside. That ability was part of the latest release, so we shouldn't undo it. :wink:

**Review by Ogeon — CHANGES_REQUESTED** [review]
Thanks for submitting this PR! I had completely overlooked that there may be an `armv7-*` triple. Although some of the old functionality is still necessary, so it would be nice if you can adapt this to still preserve them.

File: build.rs (hunk 1 above)
Comment (yuhe00) [reply build.rs:14]: Yes, I agree, do you know of a way to get the compiler associated with a particular target in `build.rs`? Maybe the best would be requiring the user to specify it when run, e.g. `CC=arm-linux-gnueabihf-gcc cargo build --target=armv7-unknown-linux-gnueabihf`, since it can vary based on platform.

Comment (yuhe00) [reply build.rs:14]: Actually, it seems like the convention in rust is to use the [`cc`](https://github.com/alexcrichton/cc-rs) or [`gcc`](http://alexcrichton.com/gcc-rs/gcc/index.html) crate. I'll take a look a closer look at it when I have time.

**Comment by yuhe00** [comment]
`cc` and `glob` is apparently not very happy with Rust 1.12 :stuck_out_tongue:

File: build.rs (hunk 1 above)
Comment (Ogeon) [reply build.rs:14]: I would prefer it if we can still use the make files from wiringpi and wiringop. It would make upgrading them a bit easier if we don't have to care about any (smaller) changes in the build process... Actually these are the things I would want:

 * It should be easy to upgrade wiringpi and wiringop without having to know if their internal structure changes.
 * It should be possible to override the compiler by setting `CC` (see #16).
 * It should be possible to successfully run `cargo doc` on any platform.
 * It should be safe to accidentally run `cargo run` or even `sudo cargo run` on a development machine, without trashing the RAM or anything.

> Yes, I agree, do you know of a way to get the compiler associated with a particular target in `build.rs`?

Probably not, since there is not just one compiler per target. [These are the environment variables we get from Cargo](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts).

**Comment by Ogeon** [comment]
Seems like some people are ok with not supporting older versions, so It's fine if that test case is removed.

File: README.md [hunk 3]
```diff
@@ -48,12 +48,11 @@ fn main() {
...
 
-*The following instructions are currently outdated, so don't follow them. See other guides or [this comment](https://github.com/Ogeon/rust-on-raspberry-pi/issues/30#issuecomment-275848072) for now.*
+Follow this [guide](https://hackernoon.com/compiling-rust-for-the-raspberry-pi-49fdcd7df658).
 
-This project can be cross compiled using Cargo.
-[Follow these instructions](https://github.com/Ogeon/rust-on-raspberry-pi)
-And use `./cross64 build` or `./cross32 build`, depending on your system,
-to check if everything builds as expected.
+```
+cargo build --target=armv7-unknown-linux-gnueabihf
```
Comment (Ogeon) [inline README.md]: The travis file should be updated to follow this procedure. Otherwise it can't be recommended. It should also test with `arm-unknown-linux-gnueabihf`.

File: build.rs (hunk 1 above)
Comment (yuhe00) [reply build.rs:14]: > It should be easy to upgrade wiringpi and wiringop without having to know if their internal structure changes.

I'm not sure I agree, because there infinite many ways they could change their internal structure, and you can't cover all of the cases anyway, e.g. they could change to a completely different build system. We're pinning it to a particular version and we only use certain parts of the library, so I think this is fine.

> It should be possible to override the compiler by setting CC (see #16).

This is supported by `cc`. See the [docs](https://github.com/alexcrichton/cc-rs#external-configuration-via-environment-variables).

> It should be possible to successfully run cargo doc on any platform.
> It should be safe to accidentally run cargo run or even sudo cargo run on a development machine, without trashing the RAM or anything.

Not sure how these are relevant.

Comment (Ogeon) [reply build.rs:14]: > I'm not sure I agree, because there infinite many ways they could change their internal structure, and you can't cover all of the cases anyway, e.g. they could change to a completely different build system. We're pinning it to a particular version and we only use certain parts of the library, so I think this is fine.

What I mean is that running their make file will build the library the way they intended it to be built. I would otherwise have to inspect the make file to see if there is anything special going on.

> This is supported by cc. See the docs.

Good! :slightly_smiling_face: I just included it for completeness sake.

> Not sure how these are relevant.

Being able to run `cargo doc` is absolutely necessary for generating [the documentation at docs.rs](https://docs.rs/wiringpi/0.2.2/wiringpi/). They are running a script that just generates it for a handful of platforms and none of them are arm platforms. That's why this check we are commenting on existed in the first place.

As for the rest, wiringpi does a bunch of memory mapping and volatile writes to control the pins and I have no idea what happens if it would run on something that's not a Raspberry Pi. That's why I haven't even bothered making it compile properly for other platforms. Things throwing loud errors are pretty good indicators of not compiling for the correct architecture.

Comment (yuhe00) [reply build.rs:14]: > What I mean is that running their make file will build the library the way they intended it to be built. I would otherwise have to inspect the make file to see if there is anything special going on.

Yes, I got that. I just think if something special is indeed going on, we need take care of it explicitly anyway, on a case-by-case basis. Eg. they might split the library into multiple artifacts, how do you handle that without making changes to our build process?

> Being able to run cargo doc is absolutely necessary for generating the documentation at docs.rs. They are running a script that just generates it for a handful of platforms and none of them are arm platforms. That's why this check we are commenting on existed in the first place.

> As for the rest, wiringpi does a bunch of memory mapping and volatile writes to control the pins and I have no idea what happens if it would run on something that's not a Raspberry Pi. That's why I haven't even bothered making it compile properly for other platforms. Things throwing loud errors are pretty good indicators of not compiling for the correct architecture.

Oh, I see now :smile: I added the check back in.

File: .travis.yml [hunk 4]
```diff
@@ -18,18 +17,25 @@ install:
...
   - rustup default $RUST
   - rustup target add arm-unknown-linux-gnueabihf
+  - rustup target add armv7-unknown-linux-gnueabihf
   - rustc -V
   - cargo -V
   - cp scripts/config ~/.cargo/config
   - git clone https://github.com/raspberrypi/tools.git ~/pi-tools
   - cp scripts/gcc-sysroot ~/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin
   - chmod +x ~/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/gcc-sysroot
+  - export PATH="$HOME/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin:$PATH"
```
Comment (Ogeon) [inline .travis.yml:27]: So these steps are still necessary with this process? In that case I think they should be mentioned in `README.md`. Otherwise I would love to see them removed!

File: build.rs [hunk 5]
```diff
@@ -1,29 +1,31 @@
...
-        Ok(status) if !status.success() => panic!(
-            "failed to build wiringPi C library (exit code {:?})",
-            status.code()
-        ),
-        Err(e) => panic!("failed to build wiringPi C library: {}", e),
-        _ => {}
+    // only build wiringpi/wiringop for arm/armv7 platforms
+
+    let target = std::env::var("TARGET").unwrap();
+    if !(target.starts_with("arm-") || target.starts_with("armv7-")) {
```
Comment (Ogeon) [inline build.rs:17]: I wonder if it would be fine to just check for `arm` without the `-` or `v7-`... :thinking:

File: .travis.yml (hunk 4 above)
Comment (yuhe00) [reply .travis.yml:27]: Depends on where you get the toolchain from. On my setup I use [this](https://aur.archlinux.org/packages/arm-linux-gnueabihf-gcc/) from AUR, so I don't need to do this, but it's very Arch Linux-specific. If you are compiling on the RPi itself I'm guessing that's a different process as well. Should be up to the user.

File: build.rs (hunk 1 above)
Comment (Ogeon) [reply build.rs:14]: > Yes, I got that. I just think if something special is indeed going on, we need take care of it explicitly anyway, on a case-by-case basis. Eg. they might split the library into multiple artifacts, how do you handle that without making changes to our build process?

There's always a risk of changes being made, but it's more probable that the way the make file is used will be roughly the same, but what do I know? I see that there is an installation script there now, so it's already non-standard. Let's try it your way and see how it works.

File: .travis.yml (hunk 4 above)
Comment (Ogeon) [reply .travis.yml:27]: All of this is for making it prefer arm libraries over x86 ones when cross compiling. Does your AUR package just do it automatically?

**Comment by Ogeon** [comment]
I'll try to do some manual tests tomorrow on my Raspberry Pi, but this is probably good by now. :+1: @pingzing, does this fix your issue? Also, @Lindenk, I don't yet have a test for setting `CC`, so it would be awesome if you would try to run your setup with this.

**Comment by pingzing** [comment]
I'll give this a shot in both my environments tomorrow and report back. Fingers crossed, though!

**Comment by pingzing** [comment]
I can indeed confirm this works in both scenarios--cross-compilation and natively on the Pi!

**Comment by Ogeon** [comment]
Ah, that's great! Then @yuhe00 can add "closes #22" to the PR description. Did you have to do anything besides what you wrote in the issue? Just so I know if the procedure is the same as in the travis file or not.

Also, I didn't get enough time to test it myself today, but tomorrow should hopefully work. Otherwise I'll merge and fix any potential problems myself.

**Comment by pingzing** [comment]
Nope. I was able to take the repro project, swap out the dependencies in the Cargo.toml and was good to go.

**Comment by Ogeon** [comment]
Interesting, but very promising! Maybe the build process can be simplified even more.

**Review by Ogeon — APPROVED** [review]

**Comment by Ogeon** [comment]
Sorry for disappearing a bit. Let's get this merged!

**Comment by Ogeon** [comment]
Also thank you both for helping me with this!
